# Generated by Django 4.2.25 on 2026-02-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='activo',
        ),
        migrations.AddField(
            model_name='lead',
            name='clinica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='estatus',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('demo', 'Demo Agendada'), ('cerrado', 'Cliente Cerrado')], default='nuevo', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
