# Generated by Django 4.2.25 on 2026-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_lead_activo_lead_clinica_lead_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='clinica',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
