# Generated by Django 4.2.5 on 2025-09-16 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('sesion', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de sesion')),
                ('diasestancia', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Dias estancia')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Estatus de sesion')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de sesion')),
                ('proximasesion', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima sesion')),
                ('consejero', models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('aspectos', models.TextField(blank=True, null=True, verbose_name='Aspectos')),
                ('resultados', models.TextField(blank=True, null=True, verbose_name='Resultados')),
                ('seesperan', models.TextField(blank=True, null=True, verbose_name='Resultados que se esperan')),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Tareas')),
                ('quesetrabajo', models.TextField(blank=True, null=True, verbose_name='Que se trabajo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Sesión Individual',
                'verbose_name_plural': 'Sesiones Individuales',
                'ordering': ['expediente', 'sesion'],
                'unique_together': {('expediente', 'sesion')},
            },
        ),
        migrations.CreateModel(
            name='CGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('sesion', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de sesion')),
                ('diasestancia', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Dias estancia')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Estatus de sesion')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de sesion')),
                ('proximasesion', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima sesion')),
                ('consejero', models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('aspectos', models.TextField(blank=True, null=True, verbose_name='Aspectos')),
                ('resultados', models.TextField(blank=True, null=True, verbose_name='Resultados')),
                ('seesperan', models.TextField(blank=True, null=True, verbose_name='Resultados que se esperan')),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Tareas')),
                ('quesetrabajo', models.TextField(blank=True, null=True, verbose_name='Que se trabajo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('grupodeinternos', models.TextField(blank=True, null=True, verbose_name='Grupo de internos')),
            ],
            options={
                'verbose_name': 'Sesión Grupal',
                'verbose_name_plural': 'Sesiones Grupales',
                'ordering': ['expediente', 'sesion'],
                'unique_together': {('expediente', 'sesion')},
            },
        ),
        migrations.CreateModel(
            name='CFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('sesion', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de sesion')),
                ('diasestancia', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Dias estancia')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Estatus de sesion')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de sesion')),
                ('proximasesion', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima sesion')),
                ('consejero', models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('aspectos', models.TextField(blank=True, null=True, verbose_name='Aspectos')),
                ('resultados', models.TextField(blank=True, null=True, verbose_name='Resultados')),
                ('seesperan', models.TextField(blank=True, null=True, verbose_name='Resultados que se esperan')),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Tareas')),
                ('quesetrabajo', models.TextField(blank=True, null=True, verbose_name='Que se trabajo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('familiares', models.TextField(blank=True, null=True, verbose_name='Familiares')),
            ],
            options={
                'verbose_name': 'Sesión Familiar',
                'verbose_name_plural': 'Sesiones Familiares',
                'ordering': ['expediente', 'sesion'],
                'unique_together': {('expediente', 'sesion')},
            },
        ),
    ]
