# Generated by Django 4.2.25 on 2025-11-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datosgrales',
            unique_together={('clinica',)},
        ),
    ]
