# Generated by Django 4.2.5 on 2025-09-25 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_cindividual_cgrupal_cfamiliar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cgrupal',
            options={'ordering': ['fecha', 'sesion'], 'verbose_name': 'Sesión Grupal', 'verbose_name_plural': 'Sesiones Grupales'},
        ),
        migrations.AlterUniqueTogether(
            name='cgrupal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cgrupal',
            name='dinamica_utilizada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dinámica utilizada'),
        ),
        migrations.AddField(
            model_name='cgrupal',
            name='numero_participantes',
            field=models.SmallIntegerField(default=0, verbose_name='Número de participantes'),
        ),
        migrations.AddField(
            model_name='cgrupal',
            name='participantes',
            field=models.ManyToManyField(related_name='sesiones_grupales', to='mapp.internos', verbose_name='Participantes del grupo'),
        ),
        migrations.AddField(
            model_name='cgrupal',
            name='tema_sesion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tema de la sesión'),
        ),
        migrations.AlterField(
            model_name='cgrupal',
            name='diasestancia',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Días estancia'),
        ),
        migrations.AlterField(
            model_name='cgrupal',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de sesión'),
        ),
        migrations.AlterField(
            model_name='cgrupal',
            name='proximasesion',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima sesión'),
        ),
        migrations.AlterField(
            model_name='cgrupal',
            name='quesetrabajo',
            field=models.TextField(blank=True, null=True, verbose_name='Qué se trabajó'),
        ),
        migrations.AlterField(
            model_name='cgrupal',
            name='sesion',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Número de sesión'),
        ),
        migrations.AlterField(
            model_name='cgrupal',
            name='status',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Estatus de sesión'),
        ),
        migrations.RemoveField(
            model_name='cgrupal',
            name='expediente',
        ),
        migrations.RemoveField(
            model_name='cgrupal',
            name='grupodeinternos',
        ),
    ]
