# Generated by Django 4.2.25 on 2025-11-04 23:02

from django.db import migrations, models
import mapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_alter_datosgrales_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgrales',
            name='logo_clinica',
            field=models.ImageField(blank=True, help_text='Suba el logo oficial de la clínica', null=True, upload_to=mapp.models.ruta_logo_clinica, verbose_name='Logo de la Clínica'),
        ),
    ]
