# Generated by Django 4.2.25 on 2025-11-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_datosgrales_logo_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Oficina', 'Oficina'), ('Consejero', 'Consejero'), ('Psicologo(a)', 'Psicologo(a)'), ('Medico', 'Medico'), ('Psiquiatra', 'Psiquiatra'), ('Otro', 'Otro')], default='', max_length=20, null=True, verbose_name='Cargo'),
        ),
    ]
