# Generated by Django 4.2.5 on 2025-09-30 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_alter_cgrupal_options_alter_cgrupal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PConsejeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de sesion')),
                ('consejero', models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero')),
                ('alcoholydrogas', models.TextField(blank=True, null=True, verbose_name='Consumo de alcohol y drogas')),
                ('fisicaymental', models.TextField(blank=True, null=True, verbose_name='Salud fisica y mental')),
                ('areasdelavida', models.TextField(blank=True, null=True, verbose_name='Situacion en diferentes areas de la vida (familiar,social,laboral y economica')),
                ('metas', models.TextField(blank=True, null=True, verbose_name='Metas a mediano y/o largo plazo')),
                ('objetivos', models.TextField(blank=True, null=True, verbose_name='Objetivos a corto,mediano y largo plazo')),
                ('compromiso', models.TextField(blank=True, null=True, verbose_name='Compromiso del usuario a dejar el consumo')),
                ('logros', models.TextField(blank=True, null=True, verbose_name='Logro y mantenimiento de la abstinencia')),
                ('metasareasdevida', models.TextField(blank=True, null=True, verbose_name='Metas por area de vida')),
                ('prevencion', models.TextField(blank=True, null=True, verbose_name='Prevencion de recaidas')),
            ],
        ),
    ]
