# Generated by Django 4.2.25 on 2025-11-06 18:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgrales',
            name='logo_clinica',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Suba el logo oficial de la clínica', max_length=255, null=True, verbose_name='Logo de la Clínica'),
        ),
    ]
