# Generated by Django 4.2.5 on 2025-10-01 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_pconsejeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaConsejeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField()),
                ('descripcion', models.TextField(verbose_name='Descripción de la tarea')),
                ('imagen_tarea', models.ImageField(blank=True, null=True, upload_to='tareas_consejeria/%Y/%m/%d/', verbose_name='Imagen escaneada de la tarea')),
                ('completada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.internos')),
            ],
            options={
                'verbose_name': 'Tarea de Consejería',
                'verbose_name_plural': 'Tareas de Consejería',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
