# Generated by Django 4.2.5 on 2025-10-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_tareaconsejeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaconsejeria',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='tareaconsejeria',
            name='interno',
        ),
        migrations.RemoveField(
            model_name='tareaconsejeria',
            name='observaciones',
        ),
    ]
