# Generated by Django 4.2.5 on 2025-10-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_remove_tareaconsejeria_completada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaconsejeria',
            name='fecha_entrega',
        ),
    ]
