# Generated by Django 4.2.5 on 2025-10-01 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_remove_tareaconsejeria_fecha_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaAtencionPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de atencion')),
                ('psicologo', models.SmallIntegerField(blank=True, null=True, verbose_name='Psicologo')),
                ('lateralidad', models.CharField(blank=True, max_length=1, null=True, verbose_name='Lateralidad')),
                ('motivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Salud fisica y mental')),
                ('antecedentes', models.TextField(blank=True, null=True, verbose_name='Antecedentes')),
                ('instrumentos', models.TextField(blank=True, null=True, verbose_name='Instrumentos')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('resultados', models.TextField(blank=True, null=True, verbose_name='Resultados')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnosticos')),
            ],
        ),
    ]
