# Generated by Django 4.2.25 on 2025-11-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_alter_datosgrales_logo_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgrales',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Logo en Cloudinary'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='logo_clinica',
            field=models.ImageField(blank=True, help_text='Suba el logo oficial de la clínica', null=True, upload_to='', verbose_name='Logo de la Clínica'),
        ),
    ]
