# Generated by Django 4.2.25 on 2025-11-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_datosgrales_logo_url_alter_datosgrales_logo_clinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosgrales',
            name='logo_clinica',
        ),
        migrations.RemoveField(
            model_name='tareaconsejeria',
            name='imagen_tarea',
        ),
        migrations.AddField(
            model_name='tareaconsejeria',
            name='imagen_tarea_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la Tarea '),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Logo '),
        ),
    ]
