# Generated by Django 4.2.25 on 2025-11-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_remove_datosgrales_logo_clinica_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tareaconsejeria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tareaconsejeria',
            name='numero_tarea',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='No de tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='tareaconsejeria',
            unique_together={('clinica', 'expediente', 'numero_tarea')},
        ),
    ]
