# Generated by Django 4.2.5 on 2025-10-02 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_alter_hojaatencionps_lateralidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaatencionps',
            name='lateralidad',
            field=models.CharField(choices=[('Derecha', 'Derecha'), ('Izquierda', 'Izquierda')], default='Derecha', max_length=10, null=True, verbose_name='Lateralidad'),
        ),
        migrations.AlterField(
            model_name='hojaatencionps',
            name='motivo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo'),
        ),
        migrations.CreateModel(
            name='NotasEvolucionPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('sesion', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de sesion')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Estatus de sesion')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de sesion')),
                ('proximasesion', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima sesion')),
                ('psicologo', models.SmallIntegerField(blank=True, null=True, verbose_name='Psicologo')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('objetivoyplan', models.TextField(blank=True, null=True, verbose_name='Objetivo y plan terapeutico')),
                ('actividades', models.TextField(blank=True, null=True, verbose_name='Actividades')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('individualogrupal', models.CharField(choices=[('Individual', 'Individual'), ('Grupal', 'Grupal')], default='Individual', max_length=15, null=True, verbose_name='Sesion Individual o Grupal')),
                ('selograron', models.BooleanField(choices=[('Individual', 'Individual'), ('Grupal', 'Grupal')], default='Individual', max_length=15, null=True, verbose_name='Se logro objetivo?')),
            ],
            options={
                'verbose_name': 'Sesión Individual',
                'verbose_name_plural': 'Sesiones Individuales',
                'ordering': ['expediente', 'sesion'],
                'unique_together': {('expediente', 'sesion')},
            },
        ),
    ]
