# Generated by Django 4.2.25 on 2025-11-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_alter_tareaconsejeria_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaconsejeria',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción de la tarea'),
        ),
    ]
