# Generated by Django 4.2.5 on 2025-10-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_alter_hojaatencionps_lateralidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasevolucionps',
            name='selograron',
            field=models.BooleanField(default=False, null=True, verbose_name='Se logro objetivo?'),
        ),
    ]
