# Generated by Django 4.2.5 on 2025-10-06 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_alter_notasevolucionps_selograron'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de atencion')),
                ('medico', models.SmallIntegerField(blank=True, null=True, verbose_name='Medico')),
                ('motivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo')),
                ('padecimiento', models.TextField(blank=True, null=True, verbose_name='Padecimiento')),
                ('sintomas', models.TextField(blank=True, null=True, verbose_name='Sintomas')),
                ('tratamientos', models.TextField(blank=True, null=True, verbose_name='Tratamientos')),
                ('TA', models.CharField(blank=True, max_length=10, null=True, verbose_name='TA')),
                ('FC', models.CharField(blank=True, max_length=10, null=True, verbose_name='FC')),
                ('FR', models.CharField(blank=True, max_length=10, null=True, verbose_name='FR')),
                ('temperatura', models.CharField(blank=True, max_length=10, null=True, verbose_name='Temperatura')),
                ('peso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Peso')),
                ('talla', models.CharField(blank=True, max_length=10, null=True, verbose_name='Talla')),
                ('exploracion', models.TextField(blank=True, null=True, verbose_name='Exploracion')),
                ('examenmental', models.TextField(blank=True, null=True, verbose_name='Examen mental')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnostico')),
                ('pronostico', models.TextField(blank=True, null=True, verbose_name='Pronostico')),
                ('tratamientosugerido', models.TextField(blank=True, null=True, verbose_name='Tratamiento sugerido')),
            ],
        ),
    ]
