# Generated by Django 4.2.25 on 2025-11-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0012_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='ansiosoporque',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Por que?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cuadoocurrio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuando ocurrio esto?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cualcadacuandoyporque',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cual? cada cuando? y por que?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cualproblema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cual?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cualsonlascausas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuales son las causas?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='dequeforma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='De que forma?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='diasenelhospital',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='En el ultimo mes cuantos dias estuvo en el hospital por problemas relacionados con el consumo?,'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='encomparacion',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Ya no es un problema'), (1, 'EL problema es menor que antes'), (2, 'No ha cambiado'), (3, 'El problema es mas grave que antes')], null=True, verbose_name='En comparacion con las condiciones en que usted se encontraba antes de recibir el tratamiento, actualmente su consumo :'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='haestadoentratamiento',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='En el ultimo mes, ha estado en algun tratamiento ambulatorio?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='hasidoatendido',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='En el ultimo mes ha sido atendido por problemas de salud'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='metasparelfuturo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuales son sus metas para el futuro?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OBSERVACIONES : (caracterizticas relevantes y actitudes del ususario durante la entrevista, comentarios finales'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='obstaculos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuales han sido los obstaculos para mantener la abstinencia'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='quetansatisfecho',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Muy satisfecho(a)'), (1, 'Satisfecho(a)'), (2, 'Inseguro(a)'), (3, 'Insatisfecho(a)'), (4, 'Muy instisfecho(a)')], null=True, verbose_name='Que tan satisfecho esta de su vida actualmente?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='quetipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Que tipo?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='quitarselavida',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='En el ultimo mes, ha pensado en quitarse la vida?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='resultadoantidoping',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Si pudo realizar un estudio antidoping,anote aqui el resultado'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='sehaqueridoherir',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='En el ultimo mes, ha pensado en dañarse a si mismo?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='sehaqueridosuicidar',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='En el ultimo mes, ha intentado suicidarse?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='sehasentidotriste',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='En el ultimo mes ha sentido triste con frecuencia?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='sentidoansioso',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='Se ha sentido ansioso(a) con frecuencia?'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tomandomedicamento',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='Esta tomando algun medicamento por prescripcion medica o automedicandose'),
        ),
    ]
