# Generated by Django 4.2.5 on 2025-10-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0012_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='examenmental',
            field=models.TextField(blank=True, null=True, verbose_name='Examen mental (aspecto general, actitud,aliño, actividad motora,orientacion,concentracion,funciones cognitivas, etc.)'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='exploracion',
            field=models.TextField(blank=True, null=True, verbose_name='Exploracion y auscultacion'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='padecimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Padecimiento actual (inicio y evolucion de cosnumo de sustancias)'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='sintomas',
            field=models.TextField(blank=True, null=True, verbose_name='Sintomas generales (intoxicacion, abstinencia, efectos secundarios, etc.)'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='tratamientos',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamientos previos'),
        ),
    ]
