# Generated by Django 4.2.25 on 2025-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0013_seguimiento_ansiosoporque_seguimiento_cuadoocurrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
    ]
