# Generated by Django 4.2.5 on 2025-10-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0013_alter_medico_examenmental_alter_medico_exploracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Expediente')),
                ('historial', models.TextField(blank=True, null=True, verbose_name='Historial de recetas')),
            ],
        ),
    ]
