# Generated by Django 4.2.25 on 2025-11-20 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0014_seguimiento_clinica_seguimiento_consejero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OBSERVACIONES : (caracteristicas relevantes y actitudes del ususario durante la entrevista, comentarios finales'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='usadosatisfactoriamente',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Muy satisfecho(a)'), (1, 'Satisfecho(a)'), (2, 'Inseguro(a)'), (3, 'Insatisfecho(a)'), (4, 'Muy instisfecho(a)')], null=True, verbose_name='Ha utilizado satisfactoriamente algunas de las estrategias o tecnicas que aprendio durante su terapia?'),
        ),
        migrations.CreateModel(
            name='NotasSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=10, verbose_name='No.Expediente')),
                ('sesion', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de sesion')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Estatus de sesion')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de sesion')),
                ('proximasesion', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima sesion')),
                ('consejero', models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero')),
                ('objetivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objetivo')),
                ('consumodesustancias', models.TextField(blank=True, null=True, verbose_name='Consumo de sustancias')),
                ('plandeaccion', models.TextField(blank=True, null=True, verbose_name='Plan de accion para situaciones de riesgo de consumo')),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Tareas')),
                ('aspectosqueserevisaran', models.TextField(blank=True, null=True, verbose_name='Aspectos que se revisaran en el proximo seguimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Comentarios y/o Observaciones')),
                ('clinica', models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica')),
            ],
            options={
                'verbose_name': 'Sesión Individual',
                'verbose_name_plural': 'Sesiones Individuales',
                'ordering': ['expediente', 'sesion'],
                'unique_together': {('expediente', 'sesion', 'clinica')},
            },
        ),
    ]
