# Generated by Django 4.2.25 on 2025-11-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0015_alter_seguimiento_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiedad',
            name='annombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='assist',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='cfamiliar',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='cfisicas',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='cgrupal',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='cindividual',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='cmentales',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='crelaciones',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='depresion',
            name='depnombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='einicial',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='nombremedico',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del medico'),
        ),
        migrations.AddField(
            model_name='hojaatencionps',
            name='nombrepsicologo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del psicologo'),
        ),
        migrations.AddField(
            model_name='marcadores',
            name='marnombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='medico',
            name='nombremedico',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del medico'),
        ),
        migrations.AddField(
            model_name='notasevolucionps',
            name='nombrepsicologo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del psicologo'),
        ),
        migrations.AddField(
            model_name='notasseguimiento',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='pconsejeria',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='psicosis',
            name='psnombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='razones',
            name='razonesnombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='riesgos',
            name='riesgonombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='sdevida',
            name='svnombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='situacionfamiliar',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='nombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='usodrogas',
            name='udnombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
        migrations.AddField(
            model_name='valorizacion',
            name='valorizacionnombreconsejero',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del consejero'),
        ),
    ]
