# Generated by Django 4.2.25 on 2025-10-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0015_historiaclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinica', models.CharField(max_length=30, unique=True, verbose_name='ID Clínica')),
                ('nombre', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('numeroDeInternos', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ansiedad',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='assist',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='cfamiliar',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='cfisicas',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='cgrupal',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='cindividual',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='cmentales',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='crelaciones',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='datosgrales',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='depresion',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='einicial',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='estados',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='hojaatencionps',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='internos',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='marcadores',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='medico',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='notasevolucionps',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='pconsejeria',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='psicosis',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='razones',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='sdevida',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='situacionfamiliar',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='tareaconsejeria',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='usodrogas',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AddField(
            model_name='valorizacion',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='colateralesAlergias',
            field=models.BooleanField(default=False, null=True, verbose_name='Alergias '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='colateralesConsumos',
            field=models.BooleanField(default=False, null=True, verbose_name='Consumo sustancias o adicciones '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='colateralesInfectoContagiosos',
            field=models.BooleanField(default=False, null=True, verbose_name='Infecto-contagiosos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='colateralesMentales',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades mentales '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='colateralesOtros',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='colateralesPadecimientosCronicos',
            field=models.BooleanField(default=False, null=True, verbose_name='Padecimientos cronicos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='colateralesTraumaticos',
            field=models.BooleanField(default=False, null=True, verbose_name='Eventos traumaticos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='convivientesAlergias',
            field=models.BooleanField(default=False, null=True, verbose_name='Alergias '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='convivientesConsumos',
            field=models.BooleanField(default=False, null=True, verbose_name='Consumo sustancias o adicciones '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='convivientesInfectoContagiosos',
            field=models.BooleanField(default=False, null=True, verbose_name='Infecto-contagiosos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='convivientesMentales',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades mentales '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='convivientesOtros',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='convivientesPadecimientosCronicos',
            field=models.BooleanField(default=False, null=True, verbose_name='Padecimientos cronicos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='convivientesTraumaticos',
            field=models.BooleanField(default=False, null=True, verbose_name='Eventos traumaticos'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='conyugeTraumaticos',
            field=models.BooleanField(default=False, null=True, verbose_name='Eventos traumaticos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='conyugueAlergias',
            field=models.BooleanField(default=False, null=True, verbose_name='Alergias '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='conyugueConsumos',
            field=models.BooleanField(default=False, null=True, verbose_name='Consumo sustancias o adicciones '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='conyugueInfectoContagiosos',
            field=models.BooleanField(default=False, null=True, verbose_name='Infecto-contagiosos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='conyugueMentales',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades mentales '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='conyugueOtros',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='conyuguePadecimientosCronicos',
            field=models.BooleanField(default=False, null=True, verbose_name='Padecimientos cronicos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hermanosAlergias',
            field=models.BooleanField(default=False, null=True, verbose_name='Alergias '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hermanosConsumos',
            field=models.BooleanField(default=False, null=True, verbose_name='Consumo sustancias o adicciones '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hermanosInfectoContagiosos',
            field=models.BooleanField(default=False, null=True, verbose_name='Infecto-contagiosos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hermanosMentales',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades mentales '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hermanosOtros',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hermanosPadecimientosCronicos',
            field=models.BooleanField(default=False, null=True, verbose_name='Padecimientos cronicos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hermanosTraumaticos',
            field=models.BooleanField(default=False, null=True, verbose_name='Eventos traumaticos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijosAlergias',
            field=models.BooleanField(default=False, null=True, verbose_name='Alergias '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijosConsumos',
            field=models.BooleanField(default=False, null=True, verbose_name='Consumo sustancias o adicciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijosInfectoContagiosos',
            field=models.BooleanField(default=False, null=True, verbose_name='Infecto-contagiosos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijosMentales',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades mentales '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijosOtros',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijosPadecimientosCronicos',
            field=models.BooleanField(default=False, null=True, verbose_name='Padecimientos cronicos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hijosTraumaticos',
            field=models.BooleanField(default=False, null=True, verbose_name='Eventos traumaticos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='padresAlergias',
            field=models.BooleanField(default=False, null=True, verbose_name='Alergias '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='padresConsumos',
            field=models.BooleanField(default=False, null=True, verbose_name='Consumo sustancias o adicciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='padresInfectoContagiosos',
            field=models.BooleanField(default=False, null=True, verbose_name='Infecto-contagiosos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='padresMentales',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades mentales'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='padresOtros',
            field=models.BooleanField(default=False, null=True, verbose_name='Otras enfermedades '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='padresPadecimientosCronicos',
            field=models.BooleanField(default=False, null=True, verbose_name='Padecimientos cronicos '),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='padresTraumaticos',
            field=models.BooleanField(default=False, null=True, verbose_name='Eventos traumaticos '),
        ),
    ]
