# Generated by Django 4.2.25 on 2025-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0016_ansiedad_annombreconsejero_assist_nombreconsejero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='medico',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Medico'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='nombremedico',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del medico'),
        ),
    ]
