# Generated by Django 4.2.25 on 2025-10-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0016_clinicas_ansiedad_clinica_assist_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
        migrations.AddField(
            model_name='cfisicas',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
        migrations.AddField(
            model_name='cmentales',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
        migrations.AddField(
            model_name='crelaciones',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
        migrations.AddField(
            model_name='einicial',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
        migrations.AddField(
            model_name='situacionfamiliar',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='consejero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Consejero'),
        ),
    ]
