# Generated by Django 4.2.25 on 2025-11-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0017_recetas_medico_recetas_nombremedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='estado',
            field=models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], default='', max_length=4, null=True, verbose_name='Estado actual'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='pais',
            field=models.CharField(blank=True, choices=[('MEX', 'Mexico'), ('USA', 'Estados Unidos De Norteamerica')], default='', max_length=3, null=True, verbose_name='Pais actual'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='restado',
            field=models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], default='', max_length=4, null=True, verbose_name='Estado '),
        ),
        migrations.AlterField(
            model_name='internos',
            name='rpais',
            field=models.CharField(blank=True, choices=[('MEX', 'Mexico'), ('USA', 'Estados Unidos De Norteamerica')], default='', max_length=3, null=True, verbose_name='Pais'),
        ),
    ]
