# Generated by Django 4.2.25 on 2025-10-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0017_assist_consejero_cfisicas_consejero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgos',
            name='clinica',
            field=models.CharField(blank=True, default='Demostracion', max_length=30, null=True, verbose_name='Clinica'),
        ),
    ]
