# Generated by Django 4.2.25 on 2025-11-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0018_alter_internos_estado_alter_internos_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgrales',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='estadonac',
            field=models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=4, null=True, verbose_name='Estado de nacimiento'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='paisnac',
            field=models.CharField(blank=True, choices=[('MEX', 'Mexico'), ('USA', 'Estados Unidos De Norteamerica')], max_length=3, null=True, verbose_name='Pais de nacimiento'),
        ),
    ]
