# Generated by Django 4.2.25 on 2025-12-04 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0020_alter_datosgrales_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Numero de recibo')),
                ('expediente', models.CharField(max_length=10, verbose_name='No.Expediente')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha')),
                ('pertenencias', models.TextField(blank=True, null=True, verbose_name='Pertenencias')),
                ('operador', models.SmallIntegerField(blank=True, null=True, verbose_name='Recibio')),
                ('testigo', models.SmallIntegerField(blank=True, null=True, verbose_name='Testigo')),
                ('nombreoperador', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del operador')),
                ('clinica', models.CharField(blank=True, default='DEMO', max_length=30, null=True, verbose_name='Clinica')),
            ],
            options={
                'ordering': ['expediente', 'fecha'],
                'unique_together': {('expediente', 'recibo', 'clinica')},
            },
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Numero de recibo')),
                ('expediente', models.CharField(max_length=10, verbose_name='No.Expediente')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha')),
                ('referencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe de movimiento')),
                ('operador', models.SmallIntegerField(blank=True, null=True, verbose_name='Operador')),
                ('nombreoperador', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del operador')),
                ('clinica', models.CharField(blank=True, default='DEMO', max_length=30, null=True, verbose_name='Clinica')),
            ],
            options={
                'ordering': ['expediente', 'fecha'],
                'unique_together': {('expediente', 'recibo', 'clinica')},
            },
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=10, verbose_name='No.Expediente')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('C', 'Cargo'), ('A', 'Abono')], max_length=1, verbose_name='Tipo de movimiento')),
                ('concepto', models.SmallIntegerField(blank=True, choices=[(0, 'Aportacion total'), (1, 'Cuota por pagar'), (2, 'Pago'), (3, 'Pago parcial'), (4, 'Cancelacion de movimiento')], default=2, verbose_name='Concepto')),
                ('referencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe de movimiento')),
                ('operador', models.SmallIntegerField(blank=True, null=True, verbose_name='Operador')),
                ('nombreoperador', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del operador')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios ')),
                ('clinica', models.CharField(blank=True, default='DEMO', max_length=30, null=True, verbose_name='Clinica')),
            ],
            options={
                'ordering': ['expediente', 'fecha', 'tipo'],
                'unique_together': {('expediente', 'clinica')},
            },
        ),
        migrations.CreateModel(
            name='Edocuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=10, verbose_name='No.Expediente')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('C', 'Cargo'), ('A', 'Abono')], max_length=1, verbose_name='Tipo de movimiento')),
                ('concepto', models.SmallIntegerField(blank=True, choices=[(0, 'Aportacion total'), (1, 'Cuota por pagar'), (2, 'Pago'), (3, 'Pago parcial'), (4, 'Cancelacion de movimiento')], default=2, verbose_name='Concepto')),
                ('referencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe de movimiento')),
                ('operador', models.SmallIntegerField(blank=True, null=True, verbose_name='Operador')),
                ('nombreoperador', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del operador')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios ')),
                ('clinica', models.CharField(blank=True, default='DEMO', max_length=30, null=True, verbose_name='Clinica')),
            ],
            options={
                'ordering': ['expediente', 'fecha', 'tipo'],
                'unique_together': {('expediente', 'clinica')},
            },
        ),
    ]
