# Generated by Django 4.2.25 on 2025-12-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0021_rotros_recibos_otros_edocuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgrales',
            name='Funcionariodos',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Funcionario dos'),
        ),
        migrations.AddField(
            model_name='datosgrales',
            name='cargodos',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cargo dos'),
        ),
        migrations.AddField(
            model_name='datosgrales',
            name='cargouno',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cargo uno'),
        ),
        migrations.AddField(
            model_name='datosgrales',
            name='funcionariouno',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Funcionario uno'),
        ),
    ]
