# Generated by Django 4.2.25 on 2025-12-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0022_datosgrales_funcionariodos_datosgrales_cargodos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosgrales',
            old_name='Funcionariodos',
            new_name='funcionariodos',
        ),
    ]
