# Generated by Django 4.2.25 on 2025-12-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0023_rename_funcionariodos_datosgrales_funcionariodos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgrales',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='password',
            field=models.CharField(blank=True, default='123456', max_length=128, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Responsable'),
        ),
    ]
