# Generated by Django 4.2.25 on 2025-12-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0024_alter_datosgrales_cargo_alter_datosgrales_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internos',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='periodopago',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'Semanal'), (14, 'Catorcenal'), (15, 'Quincenal'), ('30', 'Mensual')], default=0, null=True, verbose_name='Periodo de pago'),
        ),
    ]
