# Generated by Django 4.2.25 on 2025-12-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0025_internos_saldo_alter_internos_periodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='internos',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cuota'),
        ),
    ]
