# Generated by Django 4.2.25 on 2026-01-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0026_internos_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cuota voluntaria'),
        ),
        migrations.AlterUniqueTogether(
            name='edocuenta',
            unique_together={('expediente', 'clinica', 'referencia')},
        ),
    ]
