# Generated by Django 4.2.25 on 2026-01-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0027_alter_internos_cuota_alter_edocuenta_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edocuenta',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
    ]
