# Generated by Django 4.2.25 on 2026-01-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0028_alter_edocuenta_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edocuenta',
            name='concepto',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Aportacion total'), (1, 'Cuota por pagar'), (2, 'Cuota voluntaria'), (3, 'Abono a cuota voluntaria'), (4, 'Cancelacion de movimiento')], default=2, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='otros',
            name='concepto',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Aportacion total'), (1, 'Cuota por pagar'), (2, 'Cuota voluntaria'), (3, 'Abono a cuota voluntaria'), (4, 'Cancelacion de movimiento')], default=2, verbose_name='Concepto'),
        ),
    ]
