# Generated by Django 4.2.25 on 2026-01-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0029_alter_edocuenta_concepto_alter_otros_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otros',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='recibos',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
    ]
