# Generated by Django 4.2.25 on 2026-01-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0030_alter_otros_referencia_alter_recibos_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibos',
            name='recibo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numero de recibo'),
        ),
        migrations.AlterField(
            model_name='rotros',
            name='recibo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numero de recibo'),
        ),
    ]
