# Generated by Django 4.2.25 on 2026-01-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0031_alter_recibos_recibo_alter_rotros_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos',
            name='periodo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo Fin'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo Inicio'),
        ),
    ]
