# Generated by Django 4.2.25 on 2026-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0032_recibos_periodo_fin_recibos_periodo_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos',
            name='calleynumero',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Calle y numero'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='correoelectronico',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='cp',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='estado',
            field=models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], default='', max_length=4, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='rfc',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='sitioweb',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sitio WEB'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='calleynumero',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Calle y numero'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='correoelectronico',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='cp',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='estado',
            field=models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de México'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], default='', max_length=4, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='rfc',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='sitioweb',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sitio WEB'),
        ),
        migrations.AddField(
            model_name='rotros',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
