# Generated by Django 4.2.25 on 2026-01-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0033_recibos_calleynumero_recibos_ciudad_recibos_colonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='¿Cancelado?'),
        ),
        migrations.AddField(
            model_name='recibos',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibos',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recibos',
            name='usuario_cancela',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Usuario que cancelo'),
        ),
    ]
