# Generated by Django 4.2.25 on 2026-01-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0034_recibos_cancelado_recibos_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos',
            name='usuario_cancela_nombre',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Usuario que cancelo'),
        ),
    ]
