# Generated by Django 4.2.25 on 2026-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0035_recibos_usuario_cancela_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='permisos',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Permisos'),
        ),
    ]
