# Generated by Django 4.2.25 on 2026-01-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0037_alter_marcadores_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalansiedad',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalassist',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalcfamiliar',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalcfisicas',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalcgrupal',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalcindividual',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalcmentales',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalcrelaciones',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicaldatosgrales',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicaldepresion',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicaledocuenta',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicaleinicial',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalhistoriaclinica',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalhojaatencionps',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalinternos',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalmarcadores',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalmedico',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalnotasevolucionps',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalnotasseguimiento',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalotros',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalpconsejeria',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalpsicosis',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalrazones',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalrecetas',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalrecibos',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalriesgos',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalrotros',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalsdevida',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalseguimiento',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalsituacionfamiliar',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicaltareaconsejeria',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalusodrogas',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalusuarios',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='historicalvalorizacion',
            name='historial_usuario_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por'),
        ),
    ]
