# Generated by Django 4.2.25 on 2026-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0038_historicalansiedad_historial_usuario_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='cosumioamigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio amigo(a)'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='cosumiofamiliar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio familiar'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='cosumiohermano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio hermano(a)'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='cosumiomama',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio mama'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='cosumiopapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio papa'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='cosumiopareja',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Sustancia que consumio pareja'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='problemaamigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a amigo(a)'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='problemafamiliar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a familiar'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='problemahermano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a hermano(a)'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='problemamama',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a mama'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='problemapapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a papa'),
        ),
        migrations.AlterField(
            model_name='historicalsituacionfamiliar',
            name='problemapareja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a pareja'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='cosumioamigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio amigo(a)'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='cosumiofamiliar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio familiar'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='cosumiohermano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio hermano(a)'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='cosumiomama',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio mama'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='cosumiopapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sustancia que consumio papa'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='cosumiopareja',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Sustancia que consumio pareja'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='problemaamigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a amigo(a)'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='problemafamiliar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a familiar'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='problemahermano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a hermano(a)'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='problemamama',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a mama'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='problemapapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a papa'),
        ),
        migrations.AlterField(
            model_name='situacionfamiliar',
            name='problemapareja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Problema causado a pareja'),
        ),
    ]
