# Generated by Django 4.2.25 on 2026-02-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0039_alter_historicalsituacionfamiliar_cosumioamigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmentales',
            name='p31',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Cambios drasticos de estado de animo'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p32',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Temor'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p31',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Cambios drasticos de estado de animo'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p32',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Temor'),
        ),
    ]
