# Generated by Django 4.2.25 on 2026-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0040_alter_cmentales_p31_alter_cmentales_p32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Centro de desintoxicacion'),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento de consulta, ayuda mutua,mixto, profesional '),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alternativo o religioso '),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento de internamiento (ayuda mutua,mixto,profesional,alternativos o religioso)'),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento medico'),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento psiquiatrico '),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento psicologico '),
        ),
        migrations.AddField(
            model_name='historicaltratamientos',
            name='endonde8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Otro '),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Centro de desintoxicacion'),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento de consulta, ayuda mutua,mixto, profesional '),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alternativo o religioso '),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento de internamiento (ayuda mutua,mixto,profesional,alternativos o religioso)'),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento medico'),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento psiquiatrico '),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Tratamiento psicologico '),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='endonde8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Otro '),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp10a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp11a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp12a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp13a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp14a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp15a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp16a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp17a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp18a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp19a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp1a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp20a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp21a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp22a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp23a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp24a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp25a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp26a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp2a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp3a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp4a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp5a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp7a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp8a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='fp9a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='mamaedad',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Edad de la Madre'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='mamaescolaridad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Escolaridad de la Madre'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='mamasededica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='A que se dedica'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='papaedad',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Edad del Padre'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='papaescolaridad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Escolaridad del Padre'),
        ),
        migrations.AlterField(
            model_name='cfisicas',
            name='papasededica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='A que se dedica'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p10a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p11a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p12a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p13a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p14a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p15a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p16a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p17a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p18a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p19a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p1a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p20a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p21a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p22a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p23a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p24a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p25a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p26a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p27a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p28a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p29a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p2a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p31a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p32a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p33a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p34a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p3a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p4a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p5a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p6a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p7a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p8a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='cmentales',
            name='p9a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp10a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp11a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp12a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp13a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp14a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp15a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp16a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp17a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp18a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp19a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp1a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp20a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp21a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp22a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp23a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp24a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp25a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp26a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp27a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp28a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp29a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp2a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp30a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp31a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp32a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp33a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp34a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp35a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp36a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp37a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp38a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp39a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp3a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp40a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp41a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp42a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp43a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp44a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp45a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp46a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp47a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp48a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp49a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp4a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp50a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp51a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp5a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp6a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp7a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp8a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='crelaciones',
            name='rp9a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp10a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp11a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp12a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp13a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp14a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp15a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp16a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp17a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp18a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp19a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp1a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp20a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp21a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp22a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp23a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp24a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp25a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp26a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp2a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp3a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp4a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp5a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp7a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp8a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='fp9a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='mamaedad',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Edad de la Madre'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='mamaescolaridad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Escolaridad de la Madre'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='mamasededica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='A que se dedica'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='papaedad',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Edad del Padre'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='papaescolaridad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Escolaridad del Padre'),
        ),
        migrations.AlterField(
            model_name='historicalcfisicas',
            name='papasededica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='A que se dedica'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p10a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p11a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p12a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p13a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p14a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p15a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p16a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p17a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p18a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p19a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p1a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p20a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p21a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p22a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p23a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p24a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p25a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p26a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p27a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p28a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p29a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p2a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p31a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p32a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p33a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p34a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p3a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p4a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p5a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p6a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p7a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p8a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcmentales',
            name='p9a',
            field=models.SmallIntegerField(choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp10a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp11a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp12a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp13a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp14a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp15a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp16a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp17a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp18a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp19a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp1a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp20a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp21a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp22a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp23a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp24a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp25a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp26a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp27a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp28a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp29a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp2a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp30a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp31a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp32a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp33a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp34a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp35a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp36a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp37a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp38a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp39a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp3a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp40a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp41a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp42a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp43a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp44a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp45a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp46a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp47a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp48a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp49a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp4a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp50a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp51a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp5a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp6a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp7a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp8a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicalcrelaciones',
            name='rp9a',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Nada'), (2, 'Poco'), (3, 'Regular'), (4, 'Bastante')], default=1, null=True, verbose_name='Afectacion'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='a8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol '),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='c8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='d8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h5',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h6',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h7',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='h8',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r5',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r6',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r7',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='r8',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='historicaltratamientos',
            name='recibio',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Recibio tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='a8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Alcohol '),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='c8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Concluyo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d1',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d2',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d3',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d4',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d5',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d6',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d7',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='d8',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Drogas'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h5',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h6',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h7',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='h8',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hace cuanto tiempo'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r5',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r6',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r7',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='r8',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Motivo en caso de que no'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='recibio',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, null=True, verbose_name='Recibio tratamiento'),
        ),
    ]
