# Generated by Django 4.2.25 on 2026-05-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0041_historicaltratamientos_endonde1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicas',
            name='cuanto_paga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cuánto paga'),
        ),
        migrations.AddField(
            model_name='clinicas',
            name='dias_gracia',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Días de gracia'),
        ),
        migrations.AddField(
            model_name='clinicas',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha último pago'),
        ),
        migrations.AddField(
            model_name='clinicas',
            name='status',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('VENCIDA', 'Vencida'), ('GRACIA', 'En período de gracia')], default='ACTIVA', max_length=20, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='clinicas',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clinicas',
            name='numeroDeInternos',
            field=models.SmallIntegerField(default=0, verbose_name='Número de internos'),
        ),
        migrations.AlterField(
            model_name='clinicas',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
    ]
