# Generated by Django 4.2.25 on 2026-08-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0042_clinicas_cuanto_paga_clinicas_dias_gracia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicas',
            name='maximaCapacidad',
            field=models.SmallIntegerField(default=0, verbose_name='Maxima Capacidad'),
        ),
    ]
