# Generated by Django 4.2.25 on 2026-08-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0043_clinicas_maximacapacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicas',
            name='maximaCapacidad',
        ),
        migrations.AddField(
            model_name='datosgrales',
            name='capacidadhospedaje',
            field=models.SmallIntegerField(default=0, verbose_name='Capacidad maxima de hospedaje'),
        ),
        migrations.AddField(
            model_name='historicaldatosgrales',
            name='capacidadhospedaje',
            field=models.SmallIntegerField(default=0, verbose_name='Capacidad maxima de hospedaje'),
        ),
    ]
