# Generated by Django 4.2.25 on 2026-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0044_remove_clinicas_maximacapacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgrales',
            name='cargodos',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='cargouno',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='funcionariodos',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='En atencion a:'),
        ),
        migrations.AlterField(
            model_name='datosgrales',
            name='funcionariouno',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Jefe(a) jurisdiccion'),
        ),
        migrations.AlterField(
            model_name='historicaldatosgrales',
            name='cargodos',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='historicaldatosgrales',
            name='cargouno',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='historicaldatosgrales',
            name='funcionariodos',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='En atencion a:'),
        ),
        migrations.AlterField(
            model_name='historicaldatosgrales',
            name='funcionariouno',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Jefe(a) jurisdiccion'),
        ),
    ]
