# Generated by Django 4.2.25 on 2026-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0045_alter_datosgrales_cargodos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgrales',
            name='password',
            field=models.CharField(blank=True, default='123456', max_length=128, null=True, verbose_name='Password para accesar a la clinica'),
        ),
        migrations.AlterField(
            model_name='historicaldatosgrales',
            name='password',
            field=models.CharField(blank=True, default='123456', max_length=128, null=True, verbose_name='Password para accesar a la clinica'),
        ),
    ]
