# Generated by Django 4.2.5 on 2024-05-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='alcohol',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='analgesicos',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Analgesicos'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='anfetaminas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Anfetaminas'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='basiloscopia',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Basiloscopía'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='cocaina',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cocaina'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='contagiosas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Contagiosas'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='cristal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cristal'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='disolventes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Disolventes'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='embarazo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Embarazo'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='enfermedadesotro',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Otras enfermedades'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='fisicas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Físicas'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='marihuana',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Marihuana'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='numeroreuniones',
            field=models.SmallIntegerField(blank=True, default=False, null=True, verbose_name='No. Reuniones'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='opio',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Opio'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='padecimientos',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Padecimientos'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='proviene',
            field=models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Proviene'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='psiquiatricas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Psiquiátricas'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='rohypnol',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rohypnol'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='secantes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Secantes'),
        ),
    ]
