# Generated by Django 4.2.5 on 2024-05-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_alter_internos_alcohol_alter_internos_analgesicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='acudecon',
            field=models.CharField(choices=[('S', 'Solo'), ('A', 'Amigo'), ('F', 'Familiar'), ('O', 'Otro')], default='S', max_length=1, null=True, verbose_name='Acude con'),
        ),
        migrations.AlterField(
            model_name='internos',
            name='proviene',
            field=models.CharField(choices=[('D', 'Domiclio particular'), ('P', 'Institucion publica'), ('C', 'Institucion privada'), ('O', 'Otra')], default='D', max_length=1, null=True, verbose_name='Proviene'),
        ),
    ]
