# Generated by Django 4.2.5 on 2024-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_alter_internos_acudecon_alter_internos_proviene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='provieneotro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Otro'),
        ),
    ]
