# Generated by Django 4.2.5 on 2024-05-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_internos_provieneotro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='porcualingresa',
            field=models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Por que sustancia ingresa'),
        ),
    ]
