# Generated by Django 4.2.5 on 2025-03-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_remove_internos_id_alter_internos_aportacioninicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='numeroexpediente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='No.Expediente'),
        ),
    ]
